<?
//define("NEED_AUTH", true);
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Профиль постащика");
?>

<div class="row">
<?$APPLICATION->IncludeComponent(
	"pweb.tenderix:supplier.reg", 
	"tx_supplier_reg", 
	array(
		"JQUERY" => "N",
		"SET_TITLE" => "Y",
		"STATUS" => "1",
		"STATUS2" => "1",
		"FIELDS" => array(
			"LAST_NAME",
			"NAME",
			"SECOND_NAME",
			"NAME_COMPANY",
			"NAME_DIRECTOR",
			"NAME_ACCOUNTANT",
			"CODE_INN",
			/* 7 => "CODE_KPP",
			8 => "CODE_OKVED",
			9 => "CODE_OKPO", */
			"LEGALADDRESS_REGION",
			"LEGALADDRESS_CITY",
			// 12 => "LEGALADDRESS_INDEX",
			// 13 => "LEGALADDRESS_STREET",
			// 14 => "LEGALADDRESS_POST",
			"POSTALADDRESS_REGION",
			"POSTALADDRESS_CITY",
			// 17 => "POSTALADDRESS_INDEX",
			// 18 => "POSTALADDRESS_STREET",
			// 19 => "POSTALADDRESS_POST",
			"PHONE",
			"FAX",
			// 22 => "STATEREG_PLACE",
			"STATEREG_DATE",
			"STATEREG_NDS",
			// 24 => "STATEREG_OGRN",
			"BANKING_NAME",
			"BANKING_ACCOUNT",
			// 27 => "BANKING_ACCOUNTCORR",
			// 28 => "BANKING_BIK",
			"DOP_FIELDS_DIRECTION_ACTIVE",
			"DOP_FIELDS_SUBSCRIBE_ACTIVE",
			"DOP_FIELDS_DOCUMENT_ACTIVE",
		),
		"REG_FIELDS_REQUIRED" => array(
			"LAST_NAME",
			"NAME",
			"SECOND_NAME",
			"CODE_INN",
			"NAME_COMPANY",
			"STATEREG_DATE",
			"STATEREG_NDS",
		),
		"FIELDS2" => array(
			"LAST_NAME",
			"NAME",
			"SECOND_NAME",
			"NAME_COMPANY",
			"NAME_DIRECTOR",
			"NAME_ACCOUNTANT",
			"CODE_INN",
			/* 7 => "CODE_KPP",
			8 => "CODE_OKVED",
			9 => "CODE_OKPO", */
			"LEGALADDRESS_REGION",
			"LEGALADDRESS_CITY",
			// 12 => "LEGALADDRESS_INDEX",
			// 13 => "LEGALADDRESS_STREET",
			// 14 => "LEGALADDRESS_POST",
			"POSTALADDRESS_REGION",
			"POSTALADDRESS_CITY",
			// 17 => "POSTALADDRESS_INDEX",
			// 18 => "POSTALADDRESS_STREET",
			// 19 => "POSTALADDRESS_POST",
			"PHONE",
			"FAX",
			// 22 => "STATEREG_PLACE",
			"STATEREG_DATE",
			"STATEREG_NDS",
			// 24 => "STATEREG_OGRN",
			"BANKING_NAME",
			"BANKING_ACCOUNT",
			// 27 => "BANKING_ACCOUNTCORR",
			// 28 => "BANKING_BIK",
			"DOP_FIELDS_DIRECTION_ACTIVE",
			"DOP_FIELDS_SUBSCRIBE_ACTIVE",
			"DOP_FIELDS_DOCUMENT_ACTIVE",
		),
		"REG_FIELDS_REQUIRED2" => array(
			"LAST_NAME",
			"NAME",
			"NAME_COMPANY",
			"SECOND_NAME",
			"CODE_INN",
			"STATEREG_DATE",
			"STATEREG_NDS",
		),
		"COMPONENT_TEMPLATE" => "tx_supplier_reg"
	),
	false
);?>
</div>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>