<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Профиль постащика");
?> <?$APPLICATION->IncludeComponent("pweb.tenderix:supplier.reg", ".default", array(
	"JQUERY" => "Y",
	"SET_TITLE" => "Y",
	"STATUS" => "2",
	"STATUS2" => "1",
	"FIELDS" => array(
		0 => "LAST_NAME",
		1 => "NAME",
		2 => "SECOND_NAME",
		3 => "NAME_COMPANY",
		4 => "NAME_DIRECTOR",
		5 => "NAME_ACCOUNTANT",
		6 => "CODE_INN",
		7 => "CODE_KPP",
		8 => "CODE_OKVED",
		9 => "CODE_OKPO",
		10 => "LEGALADDRESS_REGION",
		11 => "LEGALADDRESS_CITY",
		12 => "LEGALADDRESS_INDEX",
		13 => "LEGALADDRESS_STREET",
		14 => "LEGALADDRESS_POST",
		15 => "POSTALADDRESS_REGION",
		16 => "POSTALADDRESS_CITY",
		17 => "POSTALADDRESS_INDEX",
		18 => "POSTALADDRESS_STREET",
		19 => "POSTALADDRESS_POST",
		20 => "PHONE",
		21 => "FAX",
		22 => "STATEREG_PLACE",
		23 => "STATEREG_DATE",
		24 => "STATEREG_OGRN",
		25 => "BANKING_NAME",
		26 => "BANKING_ACCOUNT",
		27 => "BANKING_ACCOUNTCORR",
		28 => "BANKING_BIK",
		29 => "DOP_FIELDS_DIRECTION_ACTIVE",
		30 => "DOP_FIELDS_SUBSCRIBE_ACTIVE",
		31 => "DOP_FIELDS_DOCUMENT_ACTIVE",
		32 => "PROP_6",
		33 => "PROP_7",
		34 => "PROP_10",
		35 => "PROP_8",
		36 => "PROP_9",
		37 => "PROP_2",
	),
	"REG_FIELDS_REQUIRED" => array(
		0 => "LAST_NAME",
		1 => "NAME",
		2 => "SECOND_NAME",
		3 => "PROP_1",
		4 => "PROP_6",
		5 => "PROP_10",
		6 => "PROP_8",
		7 => "PROP_2",
	),
	"FIELDS2" => array(
		0 => "LAST_NAME",
		1 => "NAME",
		2 => "SECOND_NAME",
		3 => "NAME_COMPANY",
		4 => "CODE_INN",
		5 => "PROP_10",
		6 => "PROP_2",
	),
	"REG_FIELDS_REQUIRED2" => array(
		0 => "LAST_NAME",
		1 => "NAME",
		2 => "NAME_COMPANY",
		3 => "CODE_INN",
		4 => "CODE_OKPO",
		5 => "LEGALADDRESS_REGION",
		6 => "PROP_1",
		7 => "PROP_6",
		8 => "PROP_7",
		9 => "PROP_2",
	)
	),
	false
);?> <?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>