CREATE TABLE IF NOT EXISTS b_tx_supplier
(
	USER_ID int(18) not null,
	NAME_COMPANY varchar(255) NOT NULL,
	NAME_DIRECTOR varchar(255) NOT NULL,
	NAME_ACCOUNTANT varchar(255) NOT NULL,
	CODE_INN varchar(255) NOT NULL,
	CODE_KPP varchar(255) NOT NULL,
	CODE_OKVED varchar(255) NOT NULL,
	CODE_OKPO varchar(255) NOT NULL,
	LEGALADDRESS_REGION varchar(255) NOT NULL,
	LEGALADDRESS_CITY varchar(255) NOT NULL,
	LEGALADDRESS_INDEX varchar(255) NOT NULL,
	LEGALADDRESS_STREET varchar(255) NOT NULL,
	LEGALADDRESS_POST varchar(255),
	POSTALADDRESS_REGION varchar(255) NOT NULL,
	POSTALADDRESS_CITY varchar(255) NOT NULL,
	POSTALADDRESS_INDEX varchar(255) NOT NULL,
	POSTALADDRESS_STREET varchar(255) NOT NULL,
	POSTALADDRESS_POST varchar(255),
	PHONE varchar(255) NOT NULL,
	FAX varchar(255),
	STATEREG_PLACE varchar(255) NOT NULL,
	STATEREG_DATE varchar(255) NOT NULL,
	STATEREG_NDS varchar(1) NULL,
	STATEREG_OGRN varchar(255) NOT NULL,
	BANKING_NAME varchar(255) NOT NULL,
	BANKING_ACCOUNT varchar(255) NOT NULL,
	BANKING_ACCOUNTCORR varchar(255) NOT NULL,
	BANKING_BIK varchar(255) NOT NULL,
	XML_ID VARCHAR(255) NULL,
	STATUS int(18) NOT NULL default '0'
);

CREATE TABLE IF NOT EXISTS b_tx_supplier_status
(   
    ID int(18) not null auto_increment,
	C_SORT int(18) default '100',
	ACTIVE char(1) not null default 'Y',
    TITLE varchar(255) NOT NULL,
    AUTH char(1) not null default 'N',
    PART char(1) not null default 'N',
    LOGO_BIG INTEGER(18) NULL,
    LOGO_SMALL INTEGER(18) NULL,
    COLOR INTEGER(18) NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_tx_buyer (
	USER_ID INTEGER(18) NOT NULL,
	COMPANY_ID INTEGER(18) NOT NULL,
    SUBSCR_OWN_LOT char(1) not null default 'N',
    USER_BIND TEXT NULL,
    UNIQUE KEY USER_ID (USER_ID)
);

CREATE TABLE IF NOT EXISTS b_tx_company
(
	ID int(18) not null auto_increment,
	C_SORT int(18) default '100',
	ACTIVE char(1) not null default 'Y',
	TIMESTAMP_X datetime not null default '0000-00-00 00:00:00',
	TITLE varchar(255) NOT NULL,
	URL varchar(255),
	DESCRIPTION text,
    CODE_INN VARCHAR(255) NOT NULL,
    CODE_KPP VARCHAR(255) NOT NULL,
    CODE_OGRN VARCHAR(255) NOT NULL,
    CODE_OKVED VARCHAR(255) NOT NULL,
    CODE_OKPO VARCHAR(255) NOT NULL,
    LEGALADDRESS_COUNTRY VARCHAR(255) NOT NULL,
    LEGALADDRESS_REGION VARCHAR(255) NOT NULL,
    LEGALADDRESS_CITY VARCHAR(255) NOT NULL,
    LEGALADDRESS_BLOCK VARCHAR(255) NOT NULL,
    LEGALADDRESS_INDEX VARCHAR(255) NOT NULL,
    LEGALADDRESS_STREET VARCHAR(255) NOT NULL, 
    LEGALADDRESS_POST VARCHAR(255) NOT NULL,
    POSTALADDRESS_COUNTRY VARCHAR(255) NOT NULL,
    POSTALADDRESS_REGION VARCHAR(255) NOT NULL,
    POSTALADDRESS_CITY VARCHAR(255) NOT NULL,
    POSTALADDRESS_BLOCK VARCHAR(255) NOT NULL,
    POSTALADDRESS_INDEX VARCHAR(255) NOT NULL, 
    POSTALADDRESS_STREET VARCHAR(255) NOT NULL,
    POSTALADDRESS_POST VARCHAR(255) NOT NULL,
    POSTALADDRESS_PHONE VARCHAR(255) NOT NULL,  
	XML_ID VARCHAR(255) NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_tx_spr (
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(255) NULL,
	ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
	C_SORT INTEGER(18) NULL DEFAULT '100',
	TIMESTAMP_X DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	XML_ID VARCHAR(255) NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_tx_spr_details (
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,

	XML_ID char(36) COLLATE utf8_unicode_ci NOT NULL DEFAULT '',

	SPR_ID INTEGER(18) NOT NULL DEFAULT '0',
	TITLE VARCHAR(255) NOT NULL,
	C_SORT INTEGER(18) NULL DEFAULT '100',
	ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
	PRIMARY KEY(ID),
	INDEX IX_B_TENDER_SPR(SPR_ID)
);

CREATE TABLE IF NOT EXISTS b_tx_section (
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(255) NOT NULL,
	ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
	C_SORT INTEGER(18) NOT NULL DEFAULT '100',
    CATALOG_ID INTEGER(18) NOT NULL DEFAULT 0,
	XML_ID VARCHAR(255) NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_tx_catalog (
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,
	TITLE VARCHAR(255) NOT NULL,
	ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
	C_SORT INTEGER(18) NOT NULL DEFAULT '100',
    CATALOG_ID INTEGER(18) NOT NULL DEFAULT 0,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_tx_prod (
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,
	SECTION_ID INTEGER(18) NOT NULL,
	TITLE VARCHAR(255) NOT NULL,
	ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
	C_SORT INTEGER(18) NOT NULL DEFAULT '100',
	UNIT_ID INTEGER(18) NOT NULL,
	XML_ID VARCHAR(255) NULL,
	PRIMARY KEY(ID),
	INDEX IX_B_TENDER_SECTION(SECTION_ID)
);

CREATE TABLE IF NOT EXISTS b_tx_prod_property (
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,
	PRODUCTS_ID INTEGER(18) NOT NULL,
	SPR_ID INTEGER(18) NULL DEFAULT '0',
	TITLE VARCHAR(255) NOT NULL,
	VALUE VARCHAR(255) NULL,
	REQUIRED CHAR(1) NULL,
	EDIT CHAR(1) NULL,
	ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
	C_SORT INTEGER(18) NOT NULL DEFAULT '100',
	PRIMARY KEY(ID),
	INDEX IX_B_TENDER_SPR(SPR_ID),
	INDEX IX_B_TENDER_PRODUCTS(PRODUCTS_ID)
);

CREATE TABLE IF NOT EXISTS b_tx_lot (
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,
  ARCHIVE char(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'N',
  END_ANALIZ char(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'N',
  LOT_END char(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'N',
  SECURITY char(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'N',
  LINKED char(32) COLLATE utf8_unicode_ci DEFAULT NULL,
  FAIL char(1) COLLATE utf8_unicode_ci DEFAULT NULL,
  QUOTES char(1) COLLATE utf8_unicode_ci NOT NULL DEFAULT 'N',
  TYPE_ID char(1) COLLATE utf8_unicode_ci NOT NULL,
	SECTION_ID INTEGER(18) NOT NULL,
	COMPANY_ID INTEGER(18) NOT NULL,
	BUYER_ID INTEGER(18) NOT NULL,
	TITLE VARCHAR(255) NOT NULL,
	TIMESTAMP_X DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	DATE_START DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	TIME_EXTENSION INTEGER(18) NOT NULL DEFAULT '0',
	TIME_UPDATE INTEGER(18) NOT NULL DEFAULT '600',
	DATE_END DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	NOTE TEXT,
	OPEN_PRICE CHAR(1) NOT NULL DEFAULT 'N',
	DATE_DELIVERY VARCHAR(255) NULL,
	LIST_ALT INTEGER(18) NULL,
	RESPONSIBLE_FIO VARCHAR(255) NULL,
	RESPONSIBLE_PHONE VARCHAR(255) NULL,
	TERM_PAYMENT_ID INTEGER(18) NULL,
	TERM_PAYMENT_VAL VARCHAR(255) NULL,
	TERM_PAYMENT_REQUIRED CHAR(1) NULL DEFAULT 'N',
	TERM_PAYMENT_EDIT CHAR(1) NULL DEFAULT 'N',
	TERM_DELIVERY_ID INTEGER(18) NULL,
	TERM_DELIVERY_VAL VARCHAR(255) NULL,
	TERM_DELIVERY_REQUIRED CHAR(1) NULL DEFAULT 'N',
	TERM_DELIVERY_EDIT CHAR(1) NULL DEFAULT 'N',
    PRIVATE char(1) NOT NULL DEFAULT 'N',
    NOTVISIBLE_PROPOSAL char(1) NOT NULL DEFAULT 'N',
    WITH_NDS CHAR(1) NULL DEFAULT 'Y',
    CURRENCY CHAR(3) NOT NULL DEFAULT 'RUB',
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_tx_lot_win (
    LOT_ID	INTEGER(18) NOT NULL,
	USER_ID	INTEGER(18) NOT NULL,
    COMMENT VARCHAR(255) NULL,
	UNIQUE KEY UK_LOT_USER (LOT_ID,USER_ID)
);

CREATE TABLE IF NOT EXISTS b_tx_spec_buyer (
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,
	LOT_ID INTEGER(18) NOT NULL,
	FULL_SPEC CHAR(1) NULL DEFAULT 'N',
	NOT_ANALOG CHAR(1) NULL DEFAULT 'N',
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_tx_spec_property_b (
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,
	SPEC_ID INTEGER(18) NOT NULL,
	TITLE VARCHAR(255) NOT NULL,
	ADD_INFO VARCHAR(255) NULL,
	COUNT INTEGER(4) NULL,
	UNIT_ID INTEGER(18) NOT NULL,
	START_PRICE double unsigned DEFAULT '0',
	STEP_PRICE double unsigned DEFAULT '0',
	PRIMARY KEY(ID),
	INDEX IX_SPEC_ID(SPEC_ID)
);

CREATE TABLE IF NOT EXISTS b_tx_prod_buyer (
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,
	LOT_ID INTEGER(18) NOT NULL,
	PRODUCTS_ID INTEGER(18) NOT NULL,
	START_PRICE double unsigned DEFAULT '0',
	STEP_PRICE double unsigned DEFAULT '0',
	COUNT INTEGER(18) NOT NULL,
	COUNT_EDIT CHAR(1) NULL DEFAULT 'N',
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_tx_prod_property_b (
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,
	PRODUCTS_PROPERTY_ID INTEGER(18) NOT NULL,
	PRODUCTS_ID INTEGER(18) NOT NULL,
	VALUE VARCHAR(255) NULL,
	REQUIRED CHAR(1) NULL DEFAULT 'N',
	EDIT CHAR(1) NULL DEFAULT 'N',
	VISIBLE CHAR(1) NULL DEFAULT 'Y',
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_tx_lot_file
(
	LOT_ID	INT(11) NOT NULL,
	FILE_ID	INT(11) NOT NULL,
	UNIQUE KEY UK_LOT_FILE (LOT_ID,FILE_ID)
);

CREATE TABLE IF NOT EXISTS b_tx_supplier_subscr
(
	USER_ID	INT(11) NOT NULL,
	SECTION_ID	INT(11) NOT NULL,
	UNIQUE KEY UK_USER_SECTION (USER_ID,SECTION_ID)
);

CREATE TABLE IF NOT EXISTS b_tx_supplier_dir
(
	USER_ID	INT(11) NOT NULL,
	SECTION_ID	INT(11) NOT NULL,
	UNIQUE KEY UK_USER_SECTION (USER_ID,SECTION_ID)
);

CREATE TABLE IF NOT EXISTS b_tx_supplier_file
(
	USER_ID	INT(11) NOT NULL,
	FILE_ID	INT(11) NOT NULL,
	UNIQUE KEY UK_USER_FILE (USER_ID,FILE_ID)
);

CREATE TABLE IF NOT EXISTS b_tx_buyer_subscribe
(
	USER_ID	INT(11) NOT NULL,
	SECTION_ID	INT(11) NOT NULL,
	UNIQUE KEY UK_USER_SECTION (USER_ID,SECTION_ID)
);

CREATE TABLE IF NOT EXISTS b_tx_proposal
(
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,
	LOT_ID INTEGER(18) NOT NULL,
        TERM_PAYMENT_VAL VARCHAR(255) NULL,
	TERM_DELIVERY_VAL VARCHAR(255) NULL,
        USER_ID	INT(11) NOT NULL,
        CURRENCY CHAR(3),
        DATE_START DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
        MESSAGE text,
        PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_tx_proposal_file
(
	PROPOSAL_ID	INT(11) NOT NULL,
	FILE_ID	INT(11) NOT NULL,
	UNIQUE KEY UK_PROPOSAL_FILE (PROPOSAL_ID,FILE_ID)
);

CREATE TABLE IF NOT EXISTS b_tx_proposal_spec
(
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,
	PROPOSAL_ID INTEGER(18) NOT NULL,
        PROPERTY_BUYER_ID INTEGER(18) NOT NULL,
        ANALOG text,
        NDS INTEGER(4) NULL,
        PRICE_NDS double unsigned DEFAULT '0',
        DATE_START DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
        PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_tx_proposal_spec_h
(
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,
	PROPOSAL_ID INTEGER(18) NOT NULL,
        PROPERTY_BUYER_ID INTEGER(18) NOT NULL,
        ANALOG text,
        NDS INTEGER(4) NULL,
        PRICE_NDS double unsigned DEFAULT '0',
        DATE_START DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
        PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_tx_prod_property_s (
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,
        PROPOSAL_ID INTEGER(18) NOT NULL,
	PRODUCTS_PROPERTY_BUYER_ID INTEGER(18) NOT NULL,
	VALUE VARCHAR(255) NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_tx_proposal_prod
(
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,
	PROPOSAL_ID INTEGER(18) NOT NULL,
        NDS INTEGER(4) NULL,
        PRICE_NDS double unsigned DEFAULT '0',
        COUNT INTEGER(18) NOT NULL,
        DATE_START DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
        PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_tx_proposal_prod_h
(
	ID INTEGER(18) NOT NULL AUTO_INCREMENT,
	PROPOSAL_ID INTEGER(18) NOT NULL,
        NDS INTEGER(4) NULL,
        PRICE_NDS double unsigned DEFAULT '0',
        COUNT INTEGER(18) NOT NULL,
        DATE_START DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
        PRIMARY KEY(ID)
);

CREATE TABLE IF NOT EXISTS b_tx_statistic (
        LOT_ID int(18) unsigned NOT NULL,
        SECTION_ID int(18) unsigned NOT NULL,
        COMPANY_ID int(18) unsigned NOT NULL,
        DATE_TIME int(18) unsigned NOT NULL,
        DATE_MONTH tinyint(3) unsigned NOT NULL,
        DATE_YEAR smallint(5) unsigned NOT NULL,
        ACTIVE char(1) NOT NULL DEFAULT 'Y',
        WIN char(1) NOT NULL DEFAULT 'N',
        PRICE_MAX double unsigned DEFAULT '0',
        PRICE_MIN double unsigned DEFAULT '0',
        RIGHT_PRICE_MAX double unsigned DEFAULT '0',
        RIGHT_PRICE_MIN double unsigned DEFAULT '0',
        UNIQUE KEY LOT_ID (LOT_ID)
);

CREATE TABLE IF NOT EXISTS b_tx_supplier_propval (
        ID INTEGER(18) NOT NULL AUTO_INCREMENT,
        PROPERTY_ID INTEGER(18) NOT NULL,
        USER_ID INTEGER(18) NOT NULL,
        VALUE text,
        PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_tx_supplier_property (
        ID INTEGER(18) NOT NULL AUTO_INCREMENT,
        TITLE VARCHAR(255) NOT NULL,
        ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
        SORT int(18) default '100',
        CODE VARCHAR(255),
        FILE_TYPE VARCHAR(200),
        PROPERTY_TYPE CHAR(1) NOT NULL DEFAULT 'S',
        IS_REQUIRED CHAR(1) NOT NULL DEFAULT 'N',
        MULTI CHAR(1) NOT NULL DEFAULT 'N',
        MULTI_CNT int(11) NULL default '1',
        ROW_COUNT int(11) default '1',
        COL_COUNT int(11) default '30',
        DEFAULT_VALUE text,
        PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_tx_log (
        ID INTEGER(18) NOT NULL AUTO_INCREMENT,
        TIMESTAMP_X DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
        EVENT VARCHAR(255) NOT NULL,
        USER_ID INTEGER(18) NOT NULL,
        OBJECT INTEGER(18) NULL default '0',
        DESCRIPTION text,
        DESCRIPTION_EX text,
        PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_tx_lot_private (
        LOT_ID	INT(18) NOT NULL,
	USER_ID	INT(18) NOT NULL,
	UNIQUE KEY UK_LOT_USER (LOT_ID,USER_ID)
);

CREATE TABLE IF NOT EXISTS b_tx_proposal_propval (
        ID INTEGER(18) NOT NULL AUTO_INCREMENT,
        PROPERTY_ID INTEGER(18) NOT NULL,
        PROPOSAL_ID INTEGER(18) NOT NULL,
        LOT_ID text COLLATE utf8_unicode_ci NOT NULL,
        VALUE text,
        PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS b_tx_proposal_property (
        ID INTEGER(18) NOT NULL AUTO_INCREMENT,
        TITLE VARCHAR(255) NOT NULL,
        DESCRIPTION text COLLATE utf8_unicode_ci NOT NULL,
        ACTIVE CHAR(1) NOT NULL DEFAULT 'Y',
        SORT int(18) default '100',
        CODE VARCHAR(255),
        FILE_TYPE VARCHAR(200),
        PROPERTY_TYPE CHAR(1) NOT NULL DEFAULT 'S',
        IS_REQUIRED CHAR(1) NOT NULL DEFAULT 'N',
        MULTI CHAR(1) NOT NULL DEFAULT 'N',
        MULTI_CNT int(11) NULL default '1',
        ROW_COUNT int(11) default '1',
        COL_COUNT int(11) default '30',
        DEFAULT_VALUE text,
        START_LOT char(1) COLLATE utf8_unicode_ci NOT NULL,
  			END_LOT char(1) COLLATE utf8_unicode_ci NOT NULL,
  			S_RIGHT char(1) COLLATE utf8_unicode_ci NOT NULL,
  			T_RIGHT char(1) COLLATE utf8_unicode_ci NOT NULL,
        PRIMARY KEY (ID)
);